// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProviders from "./providers";

import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import BranchProvider from "../components/BranchProvider";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DonRifa",
  description: "Generated by create next app",
};

import { CountryService } from "../lib/services/country";
import { cookies } from "next/headers";
import { API_NY_URL, DEFAULT_COUNTRY_CODE, DEFAULT_LANGUAGE } from "../lib/config";

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();
  const messages = await getMessages();

  // Server-side fetch

  let countries: any = [];

  try {
    const cookieStore = await cookies();

    const language =
      cookieStore.get("NEXT_LOCALE")?.value || DEFAULT_LANGUAGE;
    const country =
      cookieStore.get("C_code")?.value || DEFAULT_COUNTRY_CODE;
    const response = await fetch(`${API_NY_URL}/country`, {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
        currencycode: "USD",
        currencysymbol: Buffer.from("$").toString("base64"),
        language,
        country,
        platform: "3",
      },
      cache: "no-store", // always fresh
    });

    if (!response.ok) {
      throw new Error(`Country API failed with status ${response.status}`);
    }

    const json = await response.json();
    countries = json?.data ?? [];

  } catch (error: any) {
    console.warn("❌ Failed to fetch countries on server");
    console.warn("Message:", error.message);
  }

  return (
    <html lang={locale}>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#ededed]`}
      >


        <NextIntlClientProvider locale={locale} messages={messages}>
          <ClientProviders countries={countries}>
            <BranchProvider />
            {children}
          </ClientProviders>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
