import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Header from "../components/layout/Header"
import Footer from "../components/layout/Footer"
import PreFooterIconModule from "../components/layout/PreFooterIconModule"
import { NextIntlClientProvider } from "next-intl"
import ClientProviders from "./providers"
import { Toaster } from "sonner"
import { AuthProvider } from "../context/authContext"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "DonRifa",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className="bg-[#ededed] {`${geistSans.variable} ${geistMono.variable} antialiased`}"
      >
        <AuthProvider>
          <ClientProviders>
            <NextIntlClientProvider>
              {children}
              <Toaster
                position="top-center"
                richColors
                closeButton
              />
            </NextIntlClientProvider>
          </ClientProviders>
        </AuthProvider>
      </body>
    </html>
  )
}
