// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProviders from "./providers";

import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import BranchProvider from "../components/BranchProvider";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DonRifa",
  description: "Generated by create next app",
};

import { CountryService } from "../lib/services/country";

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();
  const messages = await getMessages();

  // Server-side fetch
  let countries: any[] = [];
  try {
    const res: any = await CountryService.getCountries();
    countries = res?.data || [];
  } catch (error) {
    console.warn("Failed to fetch countries on server", error);
  }

  return (
    <html lang={locale}>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#ededed]`}
      >


        <NextIntlClientProvider locale={locale} messages={messages}>
          <ClientProviders countries={countries}>
            <BranchProvider />
            {children}
          </ClientProviders>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
